### ISSUE TITLE
Adminstration pages not working

### ISSUE THREAD

**Issue by m39yur1p7** [eventum/eventum#1065]
**Version(s) affected**: 3.10.3

**PHP Version**: 7.3.27

**Browser and Version**: Chrome 90.0.4430.72

**Description**  
Accessing manage/projects.php throws php fatal error "Access to EntityManagerInterface forbidden when Kernel is booting"

**How to reproduce**  
Same as Description

**Possible Solution**  
May be same/related to PR's #1041 and #1061

**Additional context**  

```
[Mon Apr 19 21:39:02.657927 2021] [php7:error] [pid 10903] [client n.n.n.n:57961] PHP Fatal error:  Uncaught LogicException: Access to EntityManagerInterface forbidden when Kernel is booting in /var/https/eventum.xyz.hu/src/ServiceContainer.php:127\nStack trace:\n#0 /var/https/eventum.xyz.hu/src/Db/Doctrine.php(67): Eventum\\ServiceContainer::getEntityManager()\n#1 /var/https/eventum.xyz.hu/src/Controller/Manage/ProjectsController.php(52): Eventum\\Db\\Doctrine::__callStatic('getProjectRepos...', Array)\n#2 /var/https/eventum.xyz.hu/src/Controller/BaseController.php(70): Eventum\\Controller\\Manage\\ProjectsController->configure()\n#3 /var/https/eventum.xyz.hu/src/Controller/Manage/ManageBaseController.php(29): Eventum\\Controller\\BaseController->__construct()\n#4 /var/https/eventum.xyz.hu/htdocs/manage/projects.php(16): Eventum\\Controller\\Manage\\ManageBaseController->__construct()\n#5 {main}\n  thrown in /var/https/eventum.xyz.hu/src/ServiceContainer.php on line 127, referer: https://eventum.xyz.hu/list.php
```

**Comment by glensc** [comment]
recovered https://github.com/eventum/eventum/pull/1069 & https://github.com/eventum/eventum/pull/1070
