### ISSUE TITLE
Problems entering a project

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#1160]
**Version(s) affected**: 3.8.7

**PHP Version**: HP 8.0.5 (cli) (built: May  3 2021 11:30:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies

I have a project which was working normally, suddenly several users began to report that when they selected the project, the screen went blank.
Review is made and the following log is extracted

LOG

```
app.ERROR: Uncaught Exception Error: "Cannot instantiate abstract class Dynamic_Custom_Field_Backend" at /var/www/html/eventum-3.8.7/src/Extension/ExtensionLoader.php line 57 {"exception":"[object] (Error(code: 0): Cannot instantiate abstract class Dynamic_Custom_Field_Backend at /var/www/html/eventum-3.8.7/src/Extension/ExtensionLoader.php:57)
[stacktrace]
#0 /var/www/html/eventum-3.8.7/src/CustomField/Factory.php(24): Eventum\\Extension\\ExtensionLoader->createInstance('Dynamic_Custom_...')
#1 /var/www/html/eventum-3.8.7/src/Model/Entity/CustomField.php(399): Eventum\\CustomField\\Factory::create('Dynamic_Custom_...')
#2 /var/www/html/eventum-3.8.7/src/CustomField/Converter.php(104): Eventum\\Model\\Entity\\CustomField->getProxy()
#3 /var/www/html/eventum-3.8.7/src/CustomField/Converter.php(93): Eventum\\CustomField\\Converter->applyBackendValues(Array, 30266, NULL)
#4 /var/www/html/eventum-3.8.7/lib/eventum/class.custom_field.php(192): Eventum\\CustomField\\Converter->convertIssueCustomFields(Array, 30266, NULL)
#5 /var/www/html/eventum-3.8.7/lib/eventum/class.search.php(494): Custom_Field::getListByIssue(3, 30266)
#6 /var/www/html/eventum-3.8.7/lib/eventum/class.search.php(449): Search::applyCustomFields(Array, Array, Array, 3, 30266)
#7 /var/www/html/eventum-3.8.7/src/Controller/ListController.php(160): Search::getListing(3, Array, 0, 5)
#8 /var/www/html/eventum-3.8.7/src/Controller/BaseController.php(82): Eventum\\Controller\\ListController->prepareTemplate()
#9 /var/www/html/eventum-3.8.7/htdocs/list.php(17): Eventum\\Controller\\BaseController->run()
#10 {main}
"} 
```

**Comment by glensc** [comment]
error is correct, the class is abstract:
- https://github.com/eventum/eventum/blob/v3.10.5/lib/eventum/custom_field/class.dynamic.php#L20

probably someone defined custom field using that class: `Dynamic_Custom_Field_Backend`


remove it and if needed create instance of custom field instead:
- https://github.com/eventum/eventum/blob/v3.10.5/docs/wiki/System-Advanced/DynamicCustomFieldExample.md
