### ISSUE TITLE
Normalizer throws class not found exception

### ISSUE THREAD

**Issue by cpinfold** [eventum/eventum#526]
**Version(s) affected**: 3.6.5 on PHP 7.3.4

**Description**  
Not sure if I should report here or separately to glen/Normailzer ?
```
[2019-04-18 15:00:03] app.ERROR: Uncaught Exception Error: "Class
'Normalizer' not found" at
/PATH/TO/EVENTUM/vendor/glen/filename-normalizer/src/Normalizer.php
line 24 {"exception":"[object] (Error(code: 0): Class 'Normalizer' not
found at
/PATH/TO/EVENTUM/vendor/glen/filename-normalizer/src/Normalizer.php:24)
[stacktrace]
#0 /PATH/TO/EVENTUM/src/Attachment/Attachment.php(107):
glen\\FilenameNormalizer\\Normalizer::normalize('image.png')
#1 /PATH/TO/EVENTUM/lib/eventum/class.support.php(1281):
Eventum\\Attachment\\Attachment::create('image.png', 'image/png',
'\\x89PNG\
\
\\x1A\
\\x00\\x00\\x00\
IHD...')
#2 /PATH/TO/EVENTUM/lib/eventum/class.support.php(629):
Support::extractAttachments(20784, Object(Eventum\\Mail\\ImapMessage))
#3 /PATH/TO/EVENTUM/src/Console/Command/MailDownloadCommand.php(102):
Support::processMailMessage(Object(Eventum\\Mail\\ImapMessage), Array)
#4 /PATH/TO/EVENTUM/src/Console/Command/MailDownloadCommand.php(56):
Eventum\\Console\\Command\\MailDownloadCommand->processEmails('13')
#5 [internal function]:
Eventum\\Console\\Command\\MailDownloadCommand->Eventum\\Console\\Command\\{closure}()
#6
/PATH/TO/EVENTUM/vendor/malkusch/lock/classes/mutex/LockMutex.php(39):
call_user_func(Object(Closure))
#7 /PATH/TO/EVENTUM/src/ConcurrentLock.php(37):
malkusch\\lock\\mutex\\LockMutex->synchronized(Object(Closure))
#8 /PATH/TO/EVENTUM/src/Console/Command/MailDownloadCommand.php(57):
Eventum\\ConcurrentLock->synchronized(Object(Closure))
#9 [internal function]:
Eventum\\Console\\Command\\MailDownloadCommand->execute('Email_address@xyz...',
'imap.gmail.com', 'INBOX', false, 0)
#10 /PATH/TO/EVENTUM/vendor/php-di/invoker/src/Invoker.php(82):
call_user_func_array(Array, Array)
#11 /PATH/TO/EVENTUM/vendor/mnapoli/silly/src/Application.php(95):
Invoker\\Invoker->call(Array, Array)
#12 /PATH/TO/EVENTUM/vendor/symfony/console/Command/Command.php(253):
Silly\\Application->Silly\\{closure}(Object(Symfony\\Component\\Console\\Input\\ArgvInput),
Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /PATH/TO/EVENTUM/vendor/symfony/console/Application.php(926):
Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput),
Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /PATH/TO/EVENTUM/vendor/symfony/console/Application.php(269):
Symfony\\Component\\Console\\Application->doRunCommand(Object(Silly\\Command\\Command),
Object(Symfony\\Component\\Console\\Input\\ArgvInput),
Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /PATH/TO/EVENTUM/vendor/symfony/console/Application.php(145):
Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput),
Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /PATH/TO/EVENTUM/bin/download_emails.php(26):
Symfony\\Component\\Console\\Application->run()
#17 {main}
"}
{"file":null,"line":null,"class":null,"function":null,"memory_usage":"16
MB","memory_peak_usage":"18 MB","version":"3.6.5","usr_id":"1"}
```
**How to reproduce**  
Occurs whenever an email is received by Eventum with an attachment.

**Possible Solution**  

**Additional context**

**Comment by glensc** [comment]
`ext-intl` is required extension.

ps: use code fence markdown when pasting code blocks

**Comment by cpinfold** [comment]
Fixed the code block and Thanks - added php-intl package.
