### ISSUE TITLE
Error saving custom field attached to multiple projects

### ISSUE THREAD

**Issue by BenRMiller** [eventum/eventum#682]
**Version(s) affected**: 3.8.2

**Description**  
We've just upgraded to 3.8.2, and ran into some trouble with custom fields.

When saving a custom field that is linked to more than one project, we get an error message at the top of the screen: "An error occurred while trying to update the custom field information." Some properties are successfully saved despite the error, but any additional projects added to the custom field are not saved. It is still possible to create a new custom field with multiple projects, but updating it once created fails.

**How to reproduce**  
In Administration -> Manage Custom Fields, open an existing custom field that is linked to multiple projects. Click "Update Custom Field".

**Possible Solution**  
I've bodged a quick fix on my end by making Eventum\Model\Entity\ProjectCustomField::$projectId public.

**Additional context**  
```
[2019-09-24 11:08:57] app.ERROR: Error: Cannot access private property Eventum\Model\Entity\ProjectCustomField::$projectId in /home/eventum/eventum/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php:85
Stack trace:
#0 /home/eventum/eventum/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php(128): Doctrine\Common\Collections\Expr\ClosureExpressionVisitor::getObjectFieldValue(Object(Eventum\Model\Entity\ProjectCustomField), 'projectId')
#1 [internal function]: Doctrine\Common\Collections\Expr\ClosureExpressionVisitor::Doctrine\Common\Collections\Expr\{closure}(Object(Eventum\Model\Entity\ProjectCustomField))
#2 /home/eventum/eventum/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php(402): array_filter(Array, Object(Closure))
#3 /home/eventum/eventum/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php(655): Doctrine\Common\Collections\ArrayCollection->matching(Object(Doctrine\Common\Collections\Criteria))
#4 /home/eventum/eventum/src/Model/Repository/Traits/GetOneTrait.php(32): Doctrine\ORM\PersistentCollection->matching(Object(Doctrine\Common\Collections\Criteria))
#5 /home/eventum/eventum/src/Model/Entity/CustomField.php(563): Eventum\Model\Entity\CustomField->getOne(Object(Doctrine\ORM\PersistentCollection), 'projectId', '=', 5)
#6 /home/eventum/eventum/src/Model/Repository/CustomFieldRepository.php(357): Eventum\Model\Entity\CustomField->getProjectCustomFieldById(5)
#7 /home/eventum/eventum/src/Controller/Manage/CustomFieldsController.php(120): Eventum\Model\Repository\CustomFieldRepository->setProjectAssociation(Object(Eventum\Model\Entity\CustomField), Array)
#8 /home/eventum/eventum/src/Controller/Manage/CustomFieldsController.php(73): Eventum\Controller\Manage\CustomFieldsController->updateAction()
#9 /home/eventum/eventum/src/Controller/BaseController.php(81): Eventum\Controller\Manage\CustomFieldsController->defaultAction()
#10 /home/eventum/eventum/htdocs/manage/custom_fields.php(17): Eventum\Controller\BaseController->run()
#11 {main} [] {"url":"/manage/custom_fields.php?cat=edit&id=1","ip":"192.168.168.86","http_method":"POST","server":"eventum.sterlingmutuals.com","referrer":"http://eventum.sterlingmutuals.com/manage/custom_fields.php?
```

**Comment by glensc** [comment]
Interesting bug, how Doctrine behaves differently for 1 vs N entries in ArrayCollection.

Should be fixed with #683
