### ISSUE TITLE
[POTENTIAL BUG] Exception when running search using Sphinx as FullText backend.

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#926]
**Version(s) affected**: 3.8.6

**PHP Version**: 7.3.21

**Description**  

Issue when using Sphinx as FT search:
```
[2020-08-24 10:06:32] app.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Eventum\Mail\MailMessage::createFromString() must be of the type string, null given, c
alled in /var/www/eventum-3.8.6/lib/eventum/class.note.php on line 96" at /var/www/eventum-3.8.6/src/Mail/MailMessage.php line 104 {"exception":"[object] (TypeError(code: 
0): Argument 1 passed to Eventum\\Mail\\MailMessage::createFromString() must be of the type string, null given, called in /var/www/eventum-3.8.6/lib/eventum/class.note.php
 on line 96 at /var/www/eventum-3.8.6/src/Mail/MailMessage.php:104)
[stacktrace]
#0 /var/www/eventum-3.8.6/lib/eventum/class.note.php(96): Eventum\\Mail\\MailMessage::createFromString(NULL)
#1 /var/www/eventum-3.8.6/lib/eventum/search/class.sphinx_fulltext_search.php(157): Note::getDetails(251490)
#2 /var/www/eventum-3.8.6/lib/eventum/class.search.php(787): Sphinx_Fulltext_Search->getExcerpts()
#3 /var/www/eventum-3.8.6/lib/eventum/class.search.php(423): Search::getFullTextExcerpts(Array)
#4 /var/www/eventum-3.8.6/src/Controller/ListController.php(160): Search::getListing(1, Array, 0, 25)
#5 /var/www/eventum-3.8.6/src/Controller/BaseController.php(82): Eventum\\Controller\\ListController->prepareTemplate()
#6 /var/www/eventum-3.8.6/htdocs/list.php(17): Eventum\\Controller\\BaseController->run()
#7 {main}
```
**How to reproduce**  

Run a fulltext search that may happen to dip into the mail tables.

**Comment by areis422** [comment]
Record for not_id=251490 looks to be intact, so I don't think it's a data issue.

**Comment by areis422** [comment]
Duplicate of #914

**Comment by glensc** [comment]
> Record for not_id=251490 looks to be intact, so I don't think it's a data issue.

what do you mean intact? according to #914 there's not_has_attachment>1 and not_full_message being null causing such exception.
